package com.topmortar.topmortarsales.model

data class ContactSales(
    var id_bid: String = "",
    var id_contact: String = "",
    var id_user: String = "",
    var is_active: String = "",
    var date_bid: String = "",
    var nama: String = "",
    var nomorhp: String = "",
    var tgl_lahir: String = "",
    var store_owner: String = "",
    var id_city: String = "",
    var maps_url: String = "",
    var address: String = "",
    var store_status: String = "",
    var ktp_owner: String = "",
    var termin_payment: String = "",
    var id_promo: String = "",
    var reputation: String = "",
    var created_at: String = "",
    var payment_method: String = "",
    var full_name: String = "",
    var username: String = "",
    var password: String = "",
    var level_user: String = "",
    var phone_user: String = "",
    var bid_limit: String = "",
    var id_distributor: String = "",
    var is_sales: String = "",
    var is_notify: String = "",
    var id_action_bid: String = "",
    var date_action_bid: String = "",
    var field_action_bid: String = "",
)
