package com.topmortar.topmortarsales.model

data class InvoiceModel(
    var id_invoice: String? = "",
    var id_surat_jalan: String? = "",
    var no_invoice: String? = "",
    var date_invoice: String? = "",
    var bill_to_name: String? = "",
    var bill_to_address: String? = "",
    var bill_to_phone: String? = "",
    var subtotal_invoice: String? = "",
    var total_invoice: String? = "",
    var status_invoice: String? = "",
    var is_printed: String? = "",
    var date_printed: String? = "",
    var no_surat_jalan: String? = "",
    var id_contact: String? = "",
    var dalivery_date: String? = "",
    var order_number: String? = "",
    var ship_to_name: String? = "",
    var ship_to_address: String? = "",
    var ship_to_phone: String? = "",
    var id_courier: String? = "",
    var id_kendaraan: String? = "",
    var is_finished: String? = "",
    var is_closing: String? = "",
    var date_closing: String? = "",
    var proof_closing: String? = "",
)
