package com.topmortar.topmortarsales.model

data class SuratJalanNotClosingModel (
    var id_surat_jalan: String ="",
    var no_surat_jalan: String ="",
    var id_contact: String ="",
    var dalivery_date: String ="",
    var order_number: String ="",
    var ship_to_name: String ="",
    var ship_to_address: String ="",
    var ship_to_phone: String ="",
    var id_courier: String ="",
    var id_kendaraan: String ="",
    var is_finished: String ="",
    var is_printed: String ="",
    var date_printed: String ="",
    var is_closing: String ="",
    var date_closing: String ="",
    var proof_closing: String ="",
    var distance: String ="",
    var is_cod: String ="",
    var nama: String ="",
    var nomorhp: String ="",
    var tgl_lahir: String ="",
    var store_owner: String ="",
    var id_city: String ="",
    var maps_url: String ="",
    var address: String ="",
    var store_status: String ="",
    var ktp_owner: String ="",
    var termin_payment: String ="",
    var id_promo: String ="",
    var reputation: String ="",
    var created_at: String ="",
    var dateProcessed: String = "",
    var deliveryId: String = "",
)